defaults: &defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: oracul
  options:
    allow_dynamic_fields: false
    identity_map_enabled: false
    include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    skip_version_check: false
    use_activesupport_time_zone: false
    use_utc: true

production:
  <<: *defaults

development:
  <<: *defaults