#!/usr/bin/env ruby
# encoding: utf-8
require 'rubygems'
require 'bundler/setup'

require 'mongoid'
require 'dbf'

ENV["MONGOID_ENV"] = ENV["MONGOID_ENV"] || 'production'

puts "Loading #{ENV['MONGOID_ENV']} environment..."

Mongoid.load!( File.join(::File.dirname(__FILE__), "config", "mongoid.yml") )
Mongoid.logger.level = Logger::WARN

require File.expand_path('../lib/ext',      __FILE__)
require File.expand_path('../lib/area',     __FILE__)
require File.expand_path('../lib/area_ip',  __FILE__)
require File.expand_path('../lib/kladr',    __FILE__)
require File.expand_path('../lib/geo_ip',   __FILE__)

puts "Create indexes..."

OraculUpdater::Area.with(safe: true).create_indexes
OraculUpdater::AreaIp.with(safe: true).create_indexes

puts "Done."

revision = 1

puts
puts "KLADR convertion..."
kladr = ::OraculUpdater::Kladr.new(revision)
kladr.
  clear_all.
  convert_areas.
  convert_streets.
  convert_houses.
  set_abbreviation.
  set_city_type.
  set_street_type.
  refresh_area_locations

puts
puts "Done."

=begin
puts
puts "Geo and ips convertion..."
geoip = ::OraculUpdater::GeoIp.new(revision)
geoip.
  clear_all.
  save_geo_and_ips

puts
puts "Done."
=end